version: "3.5"

volumes:
  laravel-mysql-data:
    driver: local

services:
  php_fpm:
    build: ./docker/php-fpm
    container_name: laravel_php_fpm
    working_dir: /var/www/
    networks:
      - laravel_network
    volumes:
      - ./:/var/www/

  nginx:
    build: ./docker/nginx
    container_name: laravel_nginx
    working_dir: /var/www/
    networks:
      - laravel_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - SERVER_NAME=laravel.test

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    networks:
      - laravel_network
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    volumes:
      - laravel-mysql-data:/var/lib/mysql

  mailhog:
    build: ./docker/mailhog
    container_name: laravel_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge